/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProDashboardRouteImport } from './routes/pro-dashboard'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfessionalsProIdRouteImport } from './routes/professionals.$proId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/pro-dashboard',
  path: '/pro-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsProIdRoute = ProfessionalsProIdRouteImport.update({
  id: '/professionals/$proId',
  path: '/professionals/$proId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pro-dashboard': typeof ProDashboardRoute
  '/services': typeof ServicesRoute
  '/professionals/$proId': typeof ProfessionalsProIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pro-dashboard': typeof ProDashboardRoute
  '/services': typeof ServicesRoute
  '/professionals/$proId': typeof ProfessionalsProIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pro-dashboard': typeof ProDashboardRoute
  '/services': typeof ServicesRoute
  '/professionals/$proId': typeof ProfessionalsProIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pro-dashboard'
    | '/services'
    | '/professionals/$proId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/pro-dashboard'
    | '/services'
    | '/professionals/$proId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pro-dashboard'
    | '/services'
    | '/professionals/$proId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProDashboardRoute: typeof ProDashboardRoute
  ServicesRoute: typeof ServicesRoute
  ProfessionalsProIdRoute: typeof ProfessionalsProIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-dashboard': {
      id: '/pro-dashboard'
      path: '/pro-dashboard'
      fullPath: '/pro-dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals/$proId': {
      id: '/professionals/$proId'
      path: '/professionals/$proId'
      fullPath: '/professionals/$proId'
      preLoaderRoute: typeof ProfessionalsProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProDashboardRoute: ProDashboardRoute,
  ServicesRoute: ServicesRoute,
  ProfessionalsProIdRoute: ProfessionalsProIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
